name: Build TWRP cho Oppo A5 2020
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build TWRP
        run: |
          echo "Bắt đầu quá trình build..."
          # Chỗ này là nơi chạy các lệnh build của bạn

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Oppo-A5-2020
          path: /home/runner/work/twrp_build_oppo/twrp_build_oppo/out/target/product/CPH1931/*.img
        
