name: Build TWRP CPH1931

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip
          
      - name: Sync TWRP Source
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.name "huy731324-create"
          git config --global user.email "huy731324@gmail.com"
          ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
          ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          
      - name: Clone Device Tree
        run: |
          cd ~/twrp
          rm -rf device/oppo/CPH1931
          mkdir -p device/oppo/CPH1931
          # Thử link 1
          git clone --depth=1 https://github.com/skylot/android_device_oppo_CPH1931.git -b twrp-11 device/oppo/CPH1931 || \
          # Nếu link 1 lỗi, dùng link 2 (Dự phòng)
          git clone --depth=1 https://github.com/twrpdtfe/android_device_oppo_CPH1931.git -b android-9.0 device/oppo/CPH1931
          
      - name: Check Tree
        run: ls -R ~/twrp/device/oppo/CPH1931



      - name: Build TWRP
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          lunch twrp_CPH1931-eng
          make recoveryimage -j$(nproc --all)
          
